ErpOnClick.HR/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ErpOnClick.DAL.Interfaces;
using ErpOnClick.ErpMain.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace ErpOnClick.ErpMain.Controllers.Ajax
{
    public class AjaxController : Controller
    {
        private IBranchService _BranchService;
        private IDivisionsService _divisionsService;
        private IDepartmentService _departmentService;
        private ISectionService _sectionService;
        private ISubSectionService _subSectionService;
        private IUnitService _unitService;
        private ITeamService _teamService;
        private IEmpsService _empService;
        private IEmpContractsService _empContractsService;

        public AjaxController(IBranchService BranchService, IEmpsService empService, IEmpContractsService empContractsService, IDivisionsService divisionsService, IDepartmentService departmentService, ISectionService sectionService, ISubSectionService subSectionService, IUnitService unitService, ITeamService teamService)
        {
            _BranchService = BranchService;
            _divisionsService = divisionsService;
            _departmentService = departmentService;
            _sectionService = sectionService;
            _subSectionService = subSectionService;
            _unitService = unitService;
            _teamService = teamService;
            _empService = empService;
            _empContractsService = empContractsService;


        }
        public IActionResult Index()
        {
            return View();
        }

        #region Cascasding Lists
        public JsonResult BranchCascading(int id)
        {
            var test = _BranchService.Find(c => c.CompanyId == id).Select(x => new { x.BranchId, x.BranchNameEn }).ToList();

            return Json(new { result = test });

        }
        public JsonResult DepartmentCascading(int id)
        {

            var department = _departmentService.Find(c => c.DivisionId == id).Select(x => new { x.DepartmentId, x.DepartmentNameEn }).ToList();

            return Json(new { result = department });

        }
        public JsonResult SectionCascading(int id)
        {

            var section = _sectionService.Find(c => c.DepartmentId == id).Select(x => new { x.SectionId, x.SectionNameEn }).ToList();

            return Json(new { result = section });

        }
        public JsonResult SubSectionCascading(int id)
        {

            var subSection = _subSectionService.Find(c => c.SectionId == id).Select(x => new { x.SubSectionId, x.SubSectionNameEn }).ToList();

            return Json(new { result = subSection });

        }
        public JsonResult UnitsCascading(int id)
        {

            var units = _unitService.Find(c => c.SubSectionId == id).Select(x => new { x.UnitId, x.UnitNameEn }).ToList();


            return Json(new { result = units });

        }
        public JsonResult TeamCascading(int id)
        {

            var units = _teamService.Find(c => c.UnitId == id).Select(x => new { x.TeamId, x.TeamEn }).ToList();


            return Json(new { result = units });

        }
        #endregion
        [HttpPost]
        public IActionResult CultureManagement(string culture, string returnurl)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });
            return LocalRedirect(returnurl);
        }
        [HttpPost]
        public JsonResult GetEmployee(string empCode)
        {
            var empJointDetails = new EmpJointDetails();
            try
            {
                var empDetails = _empService.Find(x => x.EmpCode == empCode).FirstOrDefault();
                var empContractDetails = _empContractsService.Find(x => x.EmpId == empDetails.EmpId && x.ContractStatus == "027002").FirstOrDefault();

                if (empContractDetails != null)
                {
                    empJointDetails.EmpName = empDetails.FirstNameEn + " " + empDetails.FatherNameEn;
                    empJointDetails.JobTitle = empDetails.EmpPosition;
                    empJointDetails.DepartMent = _departmentService.GetById(empContractDetails.DepartmentId).DepartmentNameEn;
                    empJointDetails.JoiningDate = empContractDetails.JoiningDate.ToString();
                    empJointDetails.ProfilePictureUrl = empDetails.ProfilePic;
                    empJointDetails.EmpId = empDetails.EmpId;

                }
                else
                {
                    return Json(new { result = "contract" });
                }

                return Json(new { result = empJointDetails });
            }
            catch (Exception ex)
            {
                return Json(new { result = "" });

            }

        }

    }
}

ErpOnClick.HR/Views/Shared/FinanceLayout/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions
@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedCultures.Select(x => new SelectListItem { Value = x.Name, Text = x.NativeName }).ToList();
    var returnurl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";

}
<div>
    <form asp-action="CultureManagement" asp-area=""  asp-controller="Ajax" method="post" asp-route-returnUrl="@returnurl">
        <select class="languageBox" name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" onchange="this.form.submit();">
        </select>
    </form>
</div>

ErpOnClick.HR/Views/Shared/FinanceLayout/_nav.cshtml
@using ErpOnClick.ErpMain.Resources
@inject LocService SharedLocalizer

<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">


        <li class="nav-item has-treeview menu-open" id="AccRli">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-receipt"></i>
                <p>
                    @SharedLocalizer.GetLocalizedHtmlString("A/c Receivables")
                    <i class="fas fa-angle-left right"></i>

                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item"><a href="~/Finance/Customers" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Customers")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Invoice" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Invoices")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Receipts" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Receipts")</p></a></li>
                <li class="nav-item"><a href="~/Finance/CreditNotes" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Credit Notes")</p></a></li>

            </ul>
        </li>
        <li class="nav-item has-treeview" id="AccPli">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-file-invoice"></i>
                <p>
                    @SharedLocalizer.GetLocalizedHtmlString("A/c Payables")
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item"><a href="~/Finance/Vendors" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Vendors")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Bills" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Bills")</p></a></li>
                <li class="nav-item"><a href="~/Finance/payments" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Payments")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Refunds" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Refunds")</p></a></li>

            </ul>
        </li>
        <li class="nav-item has-treeview" id="Accli">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-money-bill"></i>
                <p>
                    @SharedLocalizer.GetLocalizedHtmlString("Accounting")
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item"><a href="~/Finance/AccountTypes" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Account Types")</p></a></li>
                <li class="nav-item"><a href="~/Finance/AccountGroups" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Account Groups")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Accounts" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Accounts")</p></a></li>
                <li class="nav-item"><a href="~/Finance/ChartOfAccounts" class="nav-link "></i><p>@SharedLocalizer.GetLocalizedHtmlString("Chart Of Accounts")</p></a></li>
                @*<li class="nav-item"><a href="~/Finance/Vouchers" class="nav-link "><i class="fas fa-arrow-right"></i><p>@SharedLocalizer.GetLocalizedHtmlString("Vouchers")</p></a></li>*@
                <li class="nav-item"><a href="~/Finance/Vouchers" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("General Entries")</p></a></li>
                <li class="nav-item"><a href="~/Finance/FixedAsset" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Fixed Asset")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Banks" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Banks")</p></a></li>

                <li class="nav-item has-treeview" id="Reportsli">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            @SharedLocalizer.GetLocalizedHtmlString("Reports")
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item"><a href="~/Finance/TrailReport" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Trail Balance")</p></a></li>
                        <li class="nav-item"><a href="~/Finance/AccountLedger" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Account Ledger")</p></a></li>
                        @*<li class="nav-item"><a href="~/Finance/CustomerReport" class="nav-link "><p>Customer Report</p></a></li>*@
                        <li class="nav-item"><a href="~/Finance/CustomerLedgerReport" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Customer Ledger Report")</p></a></li>
                        @*<li class="nav-item"><a href="~/Finance/VendorReport" class="nav-link "><p>Vendor Report</p></a></li>*@
                        <li class="nav-item"><a href="~/Finance/VendorLedgerReport" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Vendor Ledger Report")</p></a></li>

                    </ul>
                </li>
                <li class="nav-item has-treeview" id="Statementsli">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            @SharedLocalizer.GetLocalizedHtmlString("Statements")
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item"><a href="~/Finance/ProfitLoss" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Statement of Profit & Loss")</p></a></li>
                        <li class="nav-item"><a href="~/Finance/FinancialPosition" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Statement of Financial Position")</p></a></li>
                        <li class="nav-item"><a href="~/Finance/OtherComprehensiveIncome" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Statement of Other Comprehensive Income")</p></a></li>
                        <li class="nav-item"><a href="~/Finance/ChangesInEquity" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Statement of Changes in Equity")</p></a></li>
                        <li class="nav-item"><a href="~/Finance/CashFlow" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Statement of Cash Flow")</p></a></li>

                    </ul>
                </li>
            </ul>
        </li>
        <li class="nav-item has-treeview" id="Setupli">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-cog"></i>
                <p>
                    @SharedLocalizer.GetLocalizedHtmlString("Setup")
                    <i class="fas fa-angle-left right"></i>

                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item"><a href="~/Finance/TaxRates" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Tax Rate's")</p></a></li>
                <li class="nav-item"><a href="~/Finance/Notes" class="nav-link "><p>@SharedLocalizer.GetLocalizedHtmlString("Note's")</p></a></li>
            </ul>
        </li>
        <li class="nav-item has-treeview ">

            <a href="~/home/Index" class="nav-link">
                <i class="nav-icon fas fa-sign-out-alt"></i>
                <p>
                    @SharedLocalizer.GetLocalizedHtmlString("Return")

                </p>
            </a>


        </li>
    </ul>
</nav>